// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACMC7sXDtJrzbhxd9rtmMjM9ARXkxB-DQ',
    appId: '1:461333429555:web:340e4c78256466a9bfd246',
    messagingSenderId: '461333429555',
    projectId: 'pacaitech-85277',
    authDomain: 'pacaitech-85277.firebaseapp.com',
    databaseURL: 'https://pacaitech-85277-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pacaitech-85277.firebasestorage.app',
    measurementId: 'G-HE6KMYPRXJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3A3NM4rxZNEiGT9FyDOPy-8PHQ1w_Y_I',
    appId: '1:461333429555:android:2a0323b9c3536798bfd246',
    messagingSenderId: '461333429555',
    projectId: 'pacaitech-85277',
    databaseURL: 'https://pacaitech-85277-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pacaitech-85277.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlzeJsh8_CYailDmA_nqxnMkrBurD6yIQ',
    appId: '1:461333429555:ios:be0a1a5ee1edcad4bfd246',
    messagingSenderId: '461333429555',
    projectId: 'pacaitech-85277',
    databaseURL: 'https://pacaitech-85277-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pacaitech-85277.firebasestorage.app',
    iosBundleId: 'com.example.pac',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlzeJsh8_CYailDmA_nqxnMkrBurD6yIQ',
    appId: '1:461333429555:ios:be0a1a5ee1edcad4bfd246',
    messagingSenderId: '461333429555',
    projectId: 'pacaitech-85277',
    databaseURL: 'https://pacaitech-85277-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pacaitech-85277.firebasestorage.app',
    iosBundleId: 'com.example.pac',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACMC7sXDtJrzbhxd9rtmMjM9ARXkxB-DQ',
    appId: '1:461333429555:web:79600e3bc09155d9bfd246',
    messagingSenderId: '461333429555',
    projectId: 'pacaitech-85277',
    authDomain: 'pacaitech-85277.firebaseapp.com',
    databaseURL: 'https://pacaitech-85277-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pacaitech-85277.firebasestorage.app',
    measurementId: 'G-61V9GS9YLN',
  );

}